.TH "Virgulino" 1 "02.03.2016" "1.0" "Virgulino"

.SH NAME
Virgulino - easly encryption and steganography

.SH DESCRIPTION
A easy way to encrypt messages

.SH SYNOPSIS
.B virgulino
.R -h

.B virgulino
.R -e -m <message> [-c [key]] [-v [key]] -f <filepath> -s <txt>

.B virgulino
.R -d [-c [key]] [-v [key]] -f <filepath> -s <txt>

.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
display this help and exit
.TP
\fB\-e\fR
encrypt \fB\-m\fR <\fBmessage\fR>
.TP
\fB\-d\fR
decrypt file content
.TP
\fB\-f\fR <\fBfilepath\fR>
sets the file to be used
.TP
\fB\-s\fR <\fBstealthy type\fR>
but today work only with "txt"
.TP
\fB\-c\fR [\fBkey\fR]
use caesar cypher. If \fBkey\fR isn't setted virgulino will autogenerate it
.TP
\fB\-v\fR [\fBkey\fR]
use vigenere cypher. If \fBkey\fR isn't setted virgulino will autogenerate it

.SH LampiãoSec
.RI https://lampiaosec.github.io

.RI lampiaosec[at]riseup[dot]net

.SH See more
.RI https://github.com/lampiaosec/virgulino

.SH COPYRIGHT
Copyright (C) 2016 LampiãoSec <https://lampiaosec.github.io>

This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.

.RE
