.TH "Virgulino" 3 "02.03.2016" "1.0" "Virgulino"

.SH NAME
Virgulino - easly encryption and steganography

.SH DESCRIPTION
A easy way to encrypt messages

.SH SYNOPSIS
.TP
\fB#include\fR <\fBvirgulino/cypher.h\fR>
The functions that will actually encrypt/decrypt the message.

.SH OPTIONS
.TP
\fBvirgulino/color_set.h\fR
A set of codes to define colors on output. It can be useful for many reasons.
.TP
\fBvirgulino/output.h\fR
It has every function to handle with any output provided by \fBvirgulino\fR.
.TP
\fBvirgulino/definitions.h\fR
A bunch of macros and precompiled definitions to be used on anothers headers.
.TP
\fBvirgulino/cypher_utils.h\fR
A bunch of utilitary functions to help on the cyphering/encrypting decyphering/decrypting processes.
.TP
\fBvirgulino/hide.h\fR
The steganography function.
.TP
\fBvirgulino/virgulino.h\fR
Where commandline arguments are treated and to variavles are configured to satsfy the proper arguments given by the end-user.

.SH LampiãoSec
.RI https://lampiaosec.github.io

.RI lampiaosec[at]riseup[dot]net

.SH See more
.RI https://github.com/lampiaosec/virgulino
.RE
